/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControlCenter: typeof import('./src/components/ControlCenter.vue')['default']
    GameControls: typeof import('./src/components/GameControls.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MatchTranscript: typeof import('./src/components/MatchTranscript.vue')['default']
    MatchWinner: typeof import('./src/components/MatchWinner.vue')['default']
    NewGame: typeof import('./src/components/NewGame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBoard: typeof import('./src/components/ScoreBoard.vue')['default']
    ScorePlayer: typeof import('./src/components/ScorePlayer.vue')['default']
    ScoreService: typeof import('./src/components/ScoreService.vue')['default']
    ThemeSelector: typeof import('./src/components/ThemeSelector.vue')['default']
  }
}
